#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <unistd.h>
#include <algorithm>
#include <cstring>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

constexpr int MaxPayload = 1024 * 1024;
struct Sub { std::string subject, queue, sid; int delivered = 0, max = -1; };
struct Client { int fd = -1; bool verbose = false, echo = true, headers = false; std::vector<Sub> subs; std::string in; };
static std::vector<Client> clients;
static std::map<std::string, size_t> cursors;

static void sendAll(int fd, const std::string &s) { const char *p=s.data(); size_t n=s.size(); while(n){ ssize_t w=send(fd,p,n,0); if(w<=0) return; p+=w; n-=w; } }
static std::vector<std::string> split(const std::string &s, char d) { std::vector<std::string> out; std::stringstream ss(s); std::string item; while(std::getline(ss,item,d)) out.push_back(item); return out; }
static bool subjectMatches(const std::string &pat, const std::string &subj) { auto p=split(pat,'.'), s=split(subj,'.'); size_t si=0; for(size_t pi=0; pi<p.size(); ++pi){ if(p[pi] == ">") return pi == 0 || si < s.size(); if(si >= s.size()) return false; if(p[pi] != "*" && p[pi] != s[si]) return false; ++si; } return si == s.size(); }
static void prune(Client &c) { c.subs.erase(std::remove_if(c.subs.begin(), c.subs.end(), [](const Sub &s){ return s.max == 0; }), c.subs.end()); }
static void deliver(Client &c, Sub &s, const std::string &subject, const std::string &reply, const std::string &payload, int hlen) { std::string body = payload; if(hlen >= 0 && !c.headers) body = payload.substr(hlen); if(hlen >= 0 && c.headers) sendAll(c.fd, "HMSG "+subject+" "+s.sid+(reply.empty()?" ":" "+reply+" ")+std::to_string(hlen)+" "+std::to_string(payload.size())+"\r\n"+payload+"\r\n"); else sendAll(c.fd, "MSG "+subject+" "+s.sid+(reply.empty()?" ":" "+reply+" ")+std::to_string(body.size())+"\r\n"+body+"\r\n"); if(++s.delivered >= s.max && s.max >= 0) s.max = 0; }
static void publish(size_t pub, const std::string &subject, const std::string &reply, const std::string &payload, int hlen) { std::map<std::string, std::vector<std::pair<size_t,size_t>>> queues; bool pubEcho = clients[pub].echo; for(size_t i=0;i<clients.size();++i){ if(clients[i].fd<0 || (!pubEcho && i==pub)) continue; for(size_t j=0;j<clients[i].subs.size();++j){ auto &s=clients[i].subs[j]; if(!subjectMatches(s.subject, subject)) continue; if(s.queue.empty()) deliver(clients[i], s, subject, reply, payload, hlen); else queues[s.subject+'\0'+s.queue].push_back({i,j}); } prune(clients[i]); } for(auto &[key, ms]: queues){ auto &cur=cursors[key]; auto [ci,si]=ms[cur++ % ms.size()]; if(ci<clients.size() && si<clients[ci].subs.size()) { deliver(clients[ci], clients[ci].subs[si], subject, reply, payload, hlen); prune(clients[ci]); } } }
static void ok(Client &c) { if(c.verbose) sendAll(c.fd, "+OK\r\n"); }
static void closeClient(size_t i) { if(clients[i].fd>=0) close(clients[i].fd); clients[i].fd=-1; clients[i].subs.clear(); clients[i].in.clear(); }
static void process(size_t idx, std::string line) { Client &c=clients[idx]; std::stringstream ss(line); std::vector<std::string> t; for(std::string x; ss>>x;) t.push_back(x); if(t.empty()) return; std::string op=t[0]; std::transform(op.begin(),op.end(),op.begin(),::toupper); if(op=="PING"){sendAll(c.fd,"PONG\r\n"); return;} if(op=="PONG"){ok(c); return;} if(op=="CONNECT"){ c.verbose=line.find("\"verbose\":true")!=std::string::npos; c.echo=line.find("\"echo\":false")==std::string::npos; c.headers=line.find("\"headers\":true")!=std::string::npos; ok(c); return;} if(op=="SUB" && (t.size()==3||t.size()==4)){ Sub s; s.subject=t[1]; if(t.size()==4){s.queue=t[2]; s.sid=t[3];} else s.sid=t[2]; c.subs.push_back(s); ok(c); return;} if(op=="UNSUB" && (t.size()==2||t.size()==3)){ for(auto &s:c.subs) if(s.sid==t[1]) s.max=t.size()==3?std::stoi(t[2]):0; prune(c); ok(c); return;} if((op=="PUB"||op=="HPUB") && t.size()>=3){ bool h=op=="HPUB"; std::string reply; int hlen=-1,total=0; if(!h){ reply=t.size()==4?t[2]:""; total=std::stoi(t.back()); } else { reply=t.size()==5?t[2]:""; hlen=std::stoi(t[t.size()-2]); total=std::stoi(t.back()); } if(total<0||total>MaxPayload||hlen>total){sendAll(c.fd,"-ERR 'Maximum Payload Violation'\r\n"); closeClient(idx); return;} if((int)c.in.size()<total+2) return; std::string payload=c.in.substr(0,total); c.in.erase(0,total+2); publish(idx,t[1],reply,payload,hlen); ok(c); return;} sendAll(c.fd,"-ERR 'Invalid Protocol'\r\n"); closeClient(idx); }
int main(int argc,char **argv){ int port=argc>1?std::stoi(argv[1]):4222; int l=socket(AF_INET,SOCK_STREAM,0), one=1; setsockopt(l,SOL_SOCKET,SO_REUSEADDR,&one,sizeof(one)); sockaddr_in a{}; a.sin_family=AF_INET; a.sin_addr.s_addr=INADDR_ANY; a.sin_port=htons(port); if(bind(l,(sockaddr*)&a,sizeof(a))||listen(l,256)){perror("listen"); return 1;} std::cerr << "universal-queues C++ NATS core server listening on 0.0.0.0:" << port << "\n"; while(true){ fd_set rf; FD_ZERO(&rf); FD_SET(l,&rf); int mx=l; for(auto &c:clients) if(c.fd>=0){FD_SET(c.fd,&rf); mx=std::max(mx,c.fd);} if(select(mx+1,&rf,nullptr,nullptr,nullptr)<0) continue; if(FD_ISSET(l,&rf)){ int fd=accept(l,nullptr,nullptr); Client c; c.fd=fd; clients.push_back(c); sendAll(fd,"INFO {\"server_id\":\"UCPPNATS00000000000001\",\"server_name\":\"universal-queues-cpp\",\"version\":\"0.1.0\",\"proto\":1,\"host\":\"0.0.0.0\",\"port\":"+std::to_string(port)+",\"headers\":true,\"max_payload\":"+std::to_string(MaxPayload)+"}\r\n"); } for(size_t i=0;i<clients.size();++i) if(clients[i].fd>=0 && FD_ISSET(clients[i].fd,&rf)){ char buf[8192]; ssize_t r=recv(clients[i].fd,buf,sizeof(buf),0); if(r<=0){closeClient(i); continue;} clients[i].in.append(buf,r); auto pos=clients[i].in.find('\n'); if(pos!=std::string::npos){ std::string line=clients[i].in.substr(0,pos); if(!line.empty()&&line.back()=='\r') line.pop_back(); clients[i].in.erase(0,pos+1); process(i,line); } } } }
